### ISSUE TITLE
Unable to enter date and time

### ISSUE THREAD

**Issue by axyndus** [scg-unibe-ch/ese2017-team2#5]
- When trying to add a new order on Safari with macOS Sierra I am unable to add date. 
- I get the following error:

>  Failed to convert property value of type java.lang.String to required type java.util.Date for property date; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.format.annotation.DateTimeFormat @javax.persistence.Temporal java.util.Date] for value sfhkasdhfa; nested exception is java.lang.IllegalArgumentException: Parse attempt failed for value [sfhkasdhfa]

- The reason is that safari probably doesn't fully support 'datetime-local', meaning it doesn't show a date-picker. Instead I can freely enter whatever I want.
- Our solution was to use simple text as an input and then add the annotation `@DateTimeFormat(pattern = "dd.MM.yyyy, HH:mm")` to the date variable.

**Comment by Modiseus** [comment]
The annotation `@DateTimeFormat` does not allow to add a message that gets displayed when the input is invalid.
Instead I had to add the file `messages.properties` in the directory `src/main/resources`.
In this file I added the line `typeMismatch.trip.date = has to be in the format 'yyyy-mm-ddThh:mm'.` which gets displayed if the date is in a invalid format.

I have left the input type as `datetime-local` because the browser just defaults to `text` if it does not support `datetime-local`.
